In [2]:
# importando o numpy
import numpy as np

In [3]:
# a estrutura mais simmples do numpy é um array
# semelhante a uma lista com apenas um tipo de dado
lista = [1, 2, 3, 4, 5]
array = np.array(lista)

In [4]:
# print normal
print(lista)
print(array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
#print exemplificando a diferença de tipos tipos
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
#outra forma de criar um array
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#pode ser alterado como listas
print(array[0])
array[0] = 7
print(array[0])

1
7


In [8]:
#matriz também é muito usado
#funciona similar a uma tabela com colunas e linhas
#é definida por altura e comprimento (y, x)
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#exemplo com notas

lista_notas = [8.8, 9.7, 5.9, 4.7, 0.0, 7.3]
notas = np.array(lista_notas)

In [12]:
# apesar de numpy usar funções que são nativas de python
# por já saber o tipo de dado o processamento é mais eficiente

print("Maior nota", notas.max())
print("Menor nota", notas.min())
print("Desvio padrão", notas.std())
print("Média", notas.mean())
print("Posição menor", notas.argmin())

Maior nota 9.7
Menor nota 0.0
Desvio padrão 3.1857320805254306
Média 6.066666666666666
Posição menor 4


In [ ]:
# desafio
# solicita ao usuário 10 numeros como notas
# transformar em numpy
# fazer as operações de numpy